function C021698C = importfile_event(filename, dataLines)
%IMPORTFILE Import data from a text file
%  C021698C = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a cell array.
%
%  C021698C = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  C021698C = importfile_event("/Users/zhendongzhang/Desktop/Glob_KAUST/TT_picking/Geometry/C021698C", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jan-2021 14:12:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["eventname", "C021698C"];
opts.VariableTypes = ["string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "eventname", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "eventname", "EmptyFieldRule", "auto");

% Import the data
C021698C = readtable(filename, opts);

%% Convert to output type
C021698C = table2cell(C021698C);
numIdx = cellfun(@(x) ~isnan(str2double(x)), C021698C);
C021698C(numIdx) = cellfun(@(x) {str2double(x)}, C021698C(numIdx));
end