function STATIONS1 = importfile_station_string(filename, dataLines)
%IMPORTFILE Import data from a text file
%  STATIONS1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%
%  STATIONS1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  STATIONS1 = importfile("/Users/zhendongzhang/Desktop/Glob_KAUST/TT_picking/Geometry/STATIONS.FLD.B042703C", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jan-2021 10:01:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = fixedWidthImportOptions("NumVariables", 6);

% Specify range and variable widths
opts.DataLines = dataLines;
opts.VariableWidths = [5, 10, 16, 13, 11, 7];

% Specify column names and types
opts.VariableNames = ["ATKA", "AK", "VarName3", "VarName4", "VarName5", "VarName6"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["ATKA", "AK", "VarName3", "VarName4", "VarName5", "VarName6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ATKA", "AK", "VarName3", "VarName4", "VarName5", "VarName6"], "EmptyFieldRule", "auto");

% Import the data
STATIONS1 = readmatrix(filename, opts);

end